server:
  port: 8081

spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:mysql://localhost:3306/product_db  # Update with your database name
    username: root                                # Update with your username
    password: root                            # Update with your password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update       # Options: create, update, validate, none
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
